---
- name: Setup ML Experimentation Environment
  hosts: localhost
  become: true
  vars:
    venv_path: "/home/{{ ansible_user }}/ml_env"
    jupyter_port: 8888

  tasks:
    - name: Install system packages
      apt:
        name:
          - python3-pip
          - python3-venv
          - unzip
          - curl
        state: present
        update_cache: yes

    - name: Create virtual environment
      command: "python3 -m venv {{ venv_path }}"
      args:
        creates: "{{ venv_path }}"

    - name: Upgrade pip
      command: "{{ venv_path }}/bin/pip install --upgrade pip"

    - name: Install ML packages
      pip:
        name:
          - jupyter
          - mlflow
          - tensorflow
          - torch
        virtualenv: "{{ venv_path }}"

    - name: Launch Jupyter Notebook
      command: "{{ venv_path }}/bin/jupyter notebook --ip=0.0.0.0 --port={{ jupyter_port }} --no-browser"
      async: 300
      poll: 0
      
    - name: Lauch MLflow Tracking Server
      command: "{{ venv_path }}/bin/mlflow ui --host 0.0.0.0 --port=5000"
      async: 300
      poll: 0
